version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "02:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
  - package-ecosystem: gradle
    directory: "/samples/js/kotlin-test"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
  - package-ecosystem: gradle
    directory: "/samples/jvm/junit5"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
  - package-ecosystem: maven
    directory: "/samples/jvm/maven"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
  - package-ecosystem: gradle
    directory: "/samples/jvm/kotest"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
  - package-ecosystem: gradle
    directory: "/samples/jvm/testng"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
  - package-ecosystem: gradle
    directory: "/samples/jvm/spek"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
  - package-ecosystem: gradle
    directory: "/samples/multiplatform/kotlin-test"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
