version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gr.bat assemble --no-daemon

test_script:
  - gr.bat build --no-daemon

cache:
- C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk9
  - JAVA_HOME: C:\Program Files\Java\jdk10

matrix:
  fast_finish: true
