name: Windows

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        java_version: [ 11, 17 ]

    steps:
      - uses: actions/checkout@v3
      - name: "Set up JDK 11"
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java_version }}
          cache: 'gradle'

      - name: "build using jdk ${{ matrix.java_version }}"
        env:
          JAVA_VERSION: ${{ matrix.java_version }}
        run: ./gradlew build

      # TODO 1.5.0 re-activate scala API
      #            -   name: composite build atrium-scala2
      #                run: ./gradlew build
      #                working-directory: misc\tools\atrium-scala2-test

      - name: Upload windows build code coverage
        uses: codecov/codecov-action@v3.1.4
        if: ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
        env:
          JAVA_VERSION: ${{ matrix.java_version }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: current_windows
          env_vars: JAVA_VERSION
          # too many timeout errors, let's not fail at the moment
          #fail_ci_if_error: true

      - name: composite build atrium-samples-test
        run: ./gradlew build
        working-directory: misc\tools\atrium-samples-test

      # TODO 1.2.0 activate again once we use JS IR
#      - name: composite build atrium-js-sample-test
#        run: ./gradlew build
#        working-directory: misc\tools\atrium-js-sample-test
