name: Check Generated

on:
  push:
    paths:
      - 'logic/**/main/**/*Assertions.kt'
  pull_request:
    paths:
      - 'logic/**/main/**/*Assertions.kt'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: "Set up JDK 11"
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: check generateLogic committed
        run: ./gradle/scripts/check-generateLogic-committed.sh
        shell: bash
